apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/cluster-logging-operator.openshift-logging: ""
  name: cluster-logging-operator
  namespace: openshift-logging
spec:
  channel: "5.2"
  installPlanApproval: Automatic
  name: cluster-logging-operator
  source: okd-cluster-logging
  sourceNamespace: openshift-marketplace
  startingCSV: clusterlogging.v5.2.0
