apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
     argocd.argoproj.io/sync-wave: "-1"
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat 
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
     argocd.argoproj.io/sync-wave: "-1"
  name: cluster-logging
  namespace: openshift-logging
spec:
  targetNamespaces:
  - openshift-logging
